import Head from 'next/head';
import Image from 'next/image';
import { Main } from '../components/Main';

export default function Home() {
	return (
		<div className='h-screen'>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
				<link
					href='https://fonts.googleapis.com/css2?family=Albert+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap'
					rel='stylesheet'
				/>
				<link href='https://fonts.cdnfonts.com/css/circular-std' rel='stylesheet' />
				<title>Create Next App</title>
			</Head>

			<Main />
		</div>
	);
}
